from __future__ import annotations


class ShadowBlocked(ValueError):
    pass


AUTHORITY_NOT_GRANTED = "AUTHORITY_NOT_GRANTED"
STRATEGY_ACTIVATION_BLOCKED_NO_FINANCIAL_ELIGIBILITY = "STRATEGY_ACTIVATION_BLOCKED_NO_FINANCIAL_ELIGIBILITY"
SYNTHETIC_FIXTURE_ALLOWED = "SYNTHETIC_FIXTURE_ALLOWED"

FUTURE_DATA_BLOCKED = "FUTURE_DATA_BLOCKED"
SAME_CLOSE_EXECUTION_BLOCKED = "SAME_CLOSE_EXECUTION_BLOCKED"
MISSING_DATASET_HASH = "MISSING_DATASET_HASH"
STALE_DATASET = "STALE_DATASET"
DECISION_CLOCK_INVALID = "DECISION_CLOCK_INVALID"

TARGET_PORTFOLIO_VALID = "TARGET_PORTFOLIO_VALID"
WEIGHTS_NOT_NORMALIZED = "WEIGHTS_NOT_NORMALIZED"
NEGATIVE_WEIGHT_BLOCKED = "NEGATIVE_WEIGHT_BLOCKED"
UNKNOWN_INSTRUMENT_BLOCKED = "UNKNOWN_INSTRUMENT_BLOCKED"
INELIGIBLE_INSTRUMENT_BLOCKED = "INELIGIBLE_INSTRUMENT_BLOCKED"
CONCENTRATION_LIMIT_BLOCKED = "CONCENTRATION_LIMIT_BLOCKED"
INVALID_CASH_WEIGHT = "INVALID_CASH_WEIGHT"
